version: '3'

networks:
    backend:

services:
    mysql:
        image: "mysql:${MYSQL_TAG}"
        ports:
          - 3306:3306
        volumes:
          - ./mysql:/var/lib/mysql
        env_file:
          - .env
        networks:
          - backend

    wordpress:
        image: "wordpress:${WORDPRESS_TAG}"
        ports:
          - 8000:80
        volumes:
          - ./src:/var/www/html
        env_file:
          - .env
        networks:
          - backend
        depends_on:
          - mysql
        links:
          - mysql

